- config: retrieve_irr
  uavs: 
      - {
          name: hector, fuel_rate: [0.0001, 0.00002], min_fuel: 13.0, max_fuel: 16.8, 
          deploy_system: false, retrieve_system: true, camera_system: false, irr_attached: ''
        }
  uav_waypoints:
      - {yaw: 210.0, lat: 51.42410501, long: -2.67011467, rel_alt:  10.0}
  uav_waypoint_to_wt: {WT1: 1}
  uav_waypoint_connection: [
      [0, 0, 210., 30.], [0, 1, 180., 45.], [1, 1, 510, 45]
  ]
  asvs: []
  asv_waypoints: []
  asv_waypoint_to_wt: {}
  asv_waypoint_connection: [] 
  irrs:
      - {
          name: corin, fuel_rate: [0.01, 0.05], min_fuel: 10.0, max_fuel: 100.0, ndt_system: True, repair_arm: False
        }
  irr_waypoints:
      - {yaw: 0.0, lat: 51.42410501, long: -2.67011467, repair: False, inspect: True}
  irr_waypoint_to_wt: {WT1: 1}
  irr_waypoint_connection: [
      [0, 0, 20.0, 4.], [0, 1, 300.0, 60.0], [1, 1, 300.0, 60.0]
  ]

- config: deploy_irr
  uavs: 
      - {
          name: hector, fuel_rate: [0.0001, 0.00002], min_fuel: 13.4, max_fuel: 16.8, 
          deploy_system: true, retrieve_system: false, camera_system: false, irr_attached: corin
        }
  uav_waypoints:
      - {yaw: 210.0, lat: 51.42410501, long: -2.67011467, rel_alt:  10.0}
  uav_waypoint_to_wt: {WT1: 1}
  uav_waypoint_connection: [
      [0, 0, 210., 30.], [0, 1, 180., 45.], [1, 1, 510, 45]
  ]
  asvs: []
  asv_waypoints: []
  asv_waypoint_to_wt: {}
  asv_waypoint_connection: [] 
  irrs:
      - {
          name: corin, fuel_rate: [0.01, 0.05], min_fuel: 10.0, max_fuel: 100.0, ndt_system: True, repair_arm: False
        }
  irr_waypoints:
      - {yaw: 0.0, lat: 51.42410501, long: -2.67011467, repair: False, inspect: True}
  irr_waypoint_to_wt: {WT1: 1}
  irr_waypoint_connection: [
      [0, 0, 20.0, 4.], [0, 1, 300.0, 60.0], [1, 1, 300.0, 60.0]
  ]
